# Site
title:              Meninas Digitais Piauí
bio:                "Um projeto de alunas e professoras da Universidade Federal do Piauí que visa incentivar a inserção e permanência de mulheres nas áreas de tecnologia na Universidade."
description:        "Um projeto de alunas e professoras da Universidade Federal do Piauí que visa incentivar a inserção e permanência de mulheres nas áreas de tecnologia na Universidade."
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.png'
tiled_bg:           false
locale:             pt_BR
url:                https://meninasdigitaispiaui.github.io

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   meninas-digitais-piaui

# Social
email:              meninasdigitaispiaui@gmail.com
#twitter:            username
#facebook:           username
github-url:         meninasdigitaispiaui
linkedin:           company/20522728/admin/
instagram:          meninasdigitaispiaui
#youtube-channel:   channel

# Plugins
plugins:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

collections:
    staff:
      output: true

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
